
/*
Campo id queda como AutoIncrement
*/

ALTER TABLE `tb_usuario` CHANGE `ID_USUARIO` `ID_USUARIO` INT(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `tb_usuario` CHANGE `TELEFONO` `TELEFONO` VARCHAR(11) NULL DEFAULT NULL;

ALTER TABLE `tb_usuario` CHANGE `CELULAR` `CELULAR` VARCHAR(11) NULL DEFAULT NULL;
